version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/application"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/infra"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/domain"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10