version: '3.8'
services:
  postgres:
    build: ./docker/postgres
    container_name: luxor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ramesses
      POSTGRES_DB: luxor
      POSTGRES_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d
      - ./docker/localstack/:/docker-entrypoint-init_sqsaws.d
  mock:
    image: rodolpheche/wiremock:latest-alpine
    volumes:
      - "./docker/wiremock:/home/wiremock"
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgresql-data:
    driver: local
