server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/plain,application/javascript,application/json,application/xml
    min-response-size: 1KB

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
