server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/plain,application/javascript,application/json,application/xml
    min-response-size: 1KB
  port: 8081

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  r2dbc:
    url: r2dbc:postgres://localhost:5432/luxor
    username: ${POSTGRES_USER:ramesses}
    password: ${POSTGRES_PASSWORD:secret}
    pool:
      validation-query: SELECT 1
      max-idle-time: 30m
      enabled: true
      # max-size: 10     # default
      # initial-size: 10 # default
    properties:
      sslMode: DISABLE
      schema: main

management:
  health:
    db:
      enabled: false
  server:
    port: 8082
  # https://spring.pleiades.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.exposing
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
  trace:
    http:
      # see: org.springframework.boot.actuate.trace.http.Include
      # https://spring.pleiades.io/spring-boot/docs/current/api/org/springframework/boot/actuate/trace/http/Include.html
      include: REQUEST_HEADERS, REMOTE_ADDRESS, COOKIE_HEADERS

reply:
  label:
    text: 'my best friend'

# aws
aws:
  s3:
    servers:
      local:
        host: http://localhost
        port: 4566

# api gateway
gateway:
  book-rating:
    protocol: http
    host: localhost
    port: 8080

# log
logging:
  level:
    com:
      archetype:
        luxor: DEBUG
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG # for queries
          PARAM: DEBUG # for parameters